spring:
  application:
    name: card-application-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: db-card-svc-data

application:
  decision:
    service:
      url: http://localhost:8087/api/v1/decision
dbname: db-card-svc-data



