spring:
  application:
    name: card-application-service

  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: db-card-svc-data

application:
  decision:
    service:
      url: http://decision-service:8087/api/v1/decision

dbname: db-card-svc-data

management:
  #  server:
  #    port: 8086
  security:
    enabled: false


  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'
    health:
      show-details: always
  info:
    env:
      enabled: true



