version: '3.3'

services:
  #service 1: definition of mongo database
  dereambank_db:
    image: mongo
    container_name: dereambank_db
    restart: always
    ports:
      - 27018:27017
    networks:
      - dreambank-network


  #service 2: definition of your spring-boot app
  card-application-service:                        #it is just a name, which will be used only in this file.
    image: card-application-service:latest               #name of the image after dockerfile executes
    container_name: card-application-service  #name of the container created from docker image
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGODB_HOST=dereambank_db
      - MONGODB_PORT=27017
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "8080:8080"                       #docker containter port with your os port
    networks:
      - dreambank-network
    restart: always
    depends_on:                           #define dependencies of this app
      - dereambank_db

networks:
  dreambank-network:
    external: true